export { default as Cover } from './cover/Cover'
export { default as Quote } from './quote/Quote'
export { default as Bride } from './bride/Bride'
export { default as Detail } from './detail/Detail'
export { default as Gallery } from './gallery/Gallery'
export { default as Rsvp } from './rsvp/Rsvp'